USE FreelanceSystem;

CREATE TABLE "Permissions"
(
Id INT PRIMARY KEY IDENTITY,
Permission VARCHAR(255) NOT NULL UNIQUE,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE Roles
(
Id INT PRIMARY KEY IDENTITY,
RoleName NVARCHAR(50) UNIQUE NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE RolesPermissions
(
RoleId INT NOT NULL,
PermissionId INT NOT NULL
FOREIGN KEY (PermissionId) REFERENCES "Permissions"(Id),
FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE Users
(
Id INT IDENTITY,
FirstName NVARCHAR(255) NOT NULL,
LastName NVARCHAR(255) NOT NULL,
RoleId INT  NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT GETDATE(),
Carma INT NOT NULL,
Phone NVARCHAR(13) UNIQUE,
Email NVARCHAR(13) NOT NULL UNIQUE,
UserLocation NVARCHAR(255),
PRIMARY KEY(Id),
FOREIGN KEY(RoleId) REFERENCES Roles (Id) 
	ON UPDATE CASCADE
	ON DELETE NO ACTION
);

CREATE TABLE TeamManagers
(
ManagerId INT,
Price INT,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT GETDATE(),
PRIMARY KEY(ManagerId),
FOREIGN KEY (ManagerId) REFERENCES Users (Id) 
	ON DELETE CASCADE 
	ON UPDATE CASCADE
);

CREATE TABLE CompanyContacts
(
UserId INT PRIMARY KEY,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT GETDATE(),
FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Companys
(
Id INT PRIMARY KEY IDENTITY,
OwnerId INT NOT NULL,
CompanyType TINYINT NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT GETDATE(),
FOREIGN KEY (OwnerId) REFERENCES Users(Id)
	ON DELETE CASCADE,
);

CREATE TABLE Teams
(
Id INT PRIMARY KEY IDENTITY,
CompanyId INT NOT NULL,
ManagerId INT,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT GETDATE(),
FOREIGN KEY (ManagerId) REFERENCES Users(Id),
FOREIGN KEY (CompanyId) REFERENCES Companys(Id)
	ON DELETE CASCADE,
);

CREATE TABLE Projects
(
Id INT PRIMARY KEY IDENTITY,
CustomerCompanyId INT NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT GETDATE(),
FOREIGN KEY (CustomerCompanyId) REFERENCES Companys(Id)
);

CREATE TABLE TeamsProjects
(
TeamId INT,
ProjectId INT,
FOREIGN KEY (TeamId) REFERENCES Teams(Id)
	ON DELETE CASCADE,
FOREIGN KEY (ProjectId) REFERENCES Projects(Id)
	ON DELETE CASCADE
);

CREATE TABLE Workers
(
UserId INT NOT NULL,
Price INT NOT NULL,
TeamId INT NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT GETDATE(),
PRIMARY KEY(UserId, TeamId),
FOREIGN KEY (UserId) REFERENCES Users(Id)
	ON DELETE CASCADE,
FOREIGN KEY (TeamId) REFERENCES Teams(Id)
	ON DELETE NO ACTION
);