USE FreelanceSystem;

CREATE TABLE Workers
(
UserId INT NOT NULL,
Price INT NOT NULL,
TeamId INT NOT NULL,
PRIMARY KEY(UserId, TeamId),
FOREIGN KEY (UserId) REFERENCES Users(Id)
	ON DELETE CASCADE,
FOREIGN KEY (TeamId) REFERENCES Teams(Id)
	ON DELETE CASCADE
);