Use FreelanceSystem;

CREATE TABLE Users
(
Id INT IDENTITY,
FirstName NVARCHAR(255) NOT NULL,
LastName NVARCHAR(255) NOT NULL,
RoleId INT  NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME,
Carma INT NOT NULL,
Phone NVARCHAR(13) UNIQUE,
Email NVARCHAR(13) NOT NULL UNIQUE,
UserLocation NVARCHAR(255),
PRIMARY KEY(Id),
FOREIGN KEY(RoleId) REFERENCES Roles (Id) 
	ON UPDATE CASCADE
	ON DELETE NO ACTION
);
